### ISSUE TITLE
src/index.html template not being used

### ISSUE THREAD

**Issue by n-k** [csharad/cargo-ruukh#16] opened 2018-11-06 12:21 UTC
Adding an src/index.html file with a modified template does not seem to work. Is there an example of how to use this feature?

**Comment by csharad** [comment] 2018-11-06 13:15
I have updated the README. Tell me if you are still having an issue.

**Comment by n-k** [comment] 2018-11-06 18:32
Thanks @csharad for your quick response . Works perfectly by following the updated README.

**Comment by csharad** [comment] 2018-11-07 04:48
Great! Closing this as the issue is resolved.

**Closed by csharad** 2018-11-07 04:48 UTC
